backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: darena67/redeyecpa.com

publish_mode: editorial_workflow

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: thumbnail,  label: FeaturedImage, widget: "image", required: false }