page: services
intro: "We are a one-stop-shop serving small cannabis businesses in the state of
  California. We handle all the essential accounting functions required by the
  IRS and local authorities. Eliminate your worries by outsourcing to us the
  following tasks:"
services_list:
  - title: Business and Individual
    subtitle: TAX PREPARATION & PLANNING
    desc: We provide tax preparation services for cannabis companies and their
      owners. We focus on Section 280 E mitigation and make sure that no
      possible deduction is missed. We also provide tax planning and instruct on
      forms that typically do not need our assistance, such as form 8300
    service_image: ../assets/irs-cannabis-icon.jpg
  - title: Excise, Cultivation, SUT and City tax returns
    subtitle: PREPARATION AND FILING
    desc: "With us, you will not worry about missing a deadline for Excise or City
      tax. We research local guidance, prepare your tax return, and make sure
      you pay it on time. If needed, we will contact local authorities to sort
      out a notice in the mail or previous delinquency. We also take care of
      yearly business personal property and environmental fee returns. "
    service_image: ../assets/2.jpg
  - title: Bookkeeping
    subtitle: CANNABIS AND ANCILLARY COMPANIES
    desc: "Cannabis bookkeeping can get quite complicated. If you want those
      deductions on your tax return, you need to make sure that your accounting
      is GAAP compliant. Have you heard of such things as the Absorption method,
      Accrual accounting, and Lower of Cost or Market rule? If not, it's OK
      because we know what those mean, and we will make sure you are in
      compliance. "
    service_image: ../assets/1.jpg
  - title: Point of Sale Software
    subtitle: SET UP AND AUDIT OF TAX SETTINGS
    desc: "CDTFA wants its share of Excise and SUT tax. If you under collected, the
      agency will ask you to pay the missing tax out of pocket. If you
      over-collected, the agency will want this money too! As a dispensary, you
      collect those taxes through your Point of Sale System, and very often, its
      tax settings are incorrect. We help you set up your POS tax withholdings;
      this way, you do not pay a dime less or more in tax. "
    service_image: ../assets/point-of-sale-software.jpg
  - title: IRS, FTB & CDTFA
    subtitle: REPRESENTATION
    desc: Correspond on your behalf with tax agencies. Waive penalties and interest
      and also negotiate installment plans.
    service_image: ../assets/irs-ftb-cdtfa-representation.jpg
